pms24/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('user/',include("user.urls")),
    path('project/',include("project.urls")),
]

project/urls.py
from django.urls import path
# from .views import ProjectCreationView,ProjectListView,ProjectTeamCreateView,ProjectUpdateview,ProjectDetailView,ModuleCreationView
from .views import *
from . import views

urlpatterns = [
    path("create/",ProjectCreationView.as_view(),name="project_create"),
    path("list/",ProjectListView.as_view(),name="project_list"),
    path("create_team/",ProjectTeamCreateView.as_view(),name="project_team_create"),
    path("view_team/<int:id>",views.project_team_view,name="project_team_view"),
    path("update/<int:pk>",ProjectUpdateview.as_view(),name="update_project"),
    path("detail/<int:pk>/",ProjectDetailView.as_view(),name="detail_project"),
    path("delete/<int:id>",views.delete_project,name="delete_project"),
    
    path("status/",ProjectStatusCreateView.as_view(),name="modeule_create"),
    path("create_module/",ModuleCreationView.as_view(),name="module_create"),
    path("list_module/",ModuleListView.as_view(),name="module_list"),
    path("update_module/<int:pk>",ModuleUpdateview.as_view(),name="module_update"),
    path("detail_module/<int:pk>/",ModuleDetailView.as_view(),name="module_detail"),
    path("delete_module/<int:id>",views.delete_module,name="module_delete"),
    
    path("change_status/<int:id>", views.taskStatusUpdateView, name="change_status"),
    # path("task_status_update/",views.UpdateStatusView.as_view(),name="update_status"),
    path("create_task/",TaskCreationView.as_view(),name="task_create"),
    path("list_task/",TaskListView.as_view(),name="task_list"),
    path("update_task/<int:pk>",TaskUpdateview.as_view(),name="task_update"),
    path("detail_task/<int:pk>/",TaskDetailView.as_view(),name="task_detail"),
    path("delete_task/<int:id>",views.delete_task,name="task_delete"),
    # path("total_proj",views.total_proj,name="total_projects"),
    
    path("task_assign/",TaskAssignView.as_view(),name="task_assign"),
    
    path("list_bug/",BugListView.as_view(),name="bug_list"),
    path("add_bug/",BugCreationView.as_view(),name="bug_add"),
    path("update_bug/<int:pk>",BugUpdateview.as_view(),name="bug_update"),
    path("detail_bug/<int:pk>/",BugDetailView.as_view(),name="bug_detail"),
    path("delete_bug/<int:id>",views.delete_bug,name="bug_delete"),
    # path("change_status/<int:id>", views.bugStatusUpdateView, name="change_status"),
    
]

user/urls.py
from django.contrib import admin
from django.urls import path
from .views import ManagerRegisterView,DeveloperRegisterView,UserLoginView,ManagerDashboardView,DeveloperDashboardView,UserLogoutView
from . import views

urlpatterns = [
    path("manager_register/",ManagerRegisterView.as_view(),name="manager_register"),
    path("developer_register/",DeveloperRegisterView.as_view(),name="developer_register"),
    path("login/",UserLoginView.as_view(),name="login"),
    path("manager_dashboard/",ManagerDashboardView.as_view(),name="manager_dashboard"),
    path("developer_dashboard/",DeveloperDashboardView.as_view(),name="developer_dashboard"),
    path("logout/",UserLogoutView.as_view(),name="logout"),
    
    # path("manager-dashboard/", views.   , name='manager_dashboard'),
    
    # path("sendmail/",views.sendMail,name="sendmail"),
]

project/models.py
from django.db import models
from user.models import User
# from django.utils import timezone
# default_user_value = timezone.now
# Create your models here.
techChoices = (
("Python","Python"),
("Java","Java"),
("C++","C++"),
("C#","C#"),
('Android','Android'),
)
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=100,choices=techChoices)
    estimated_hours = models.PositiveIntegerField()
    startDate = models.DateField()
    endDate = models.DateField()
    
    class Meta:
        db_table = "project"
        
    def __str__(self):
        return self.name
    
class ProjectTeam(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    class Meta:
        db_table = "projectteam"
    
    def __str__(self):
        return self.user.username

statusChoices = (
    ("Not-started","Not-started"),
    ("In-progress","In-progress"),
    ("Testing","Testing"),
    ("Completed","Completed"),
)
    
class Status(models.Model):
    status_name = models.CharField(max_length=100,choices=statusChoices)
    
    class Meta:
        db_table = "status"
    
    def __str__(self):
        return self.status_name
        
class ProjectModule(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    module_name = models.CharField(max_length=100)
    description = models.TextField()
    estimated_hours = models.PositiveIntegerField()
    status = models.ForeignKey(Status,on_delete=models.CASCADE)
    startDate = models.DateField()
    
    class Meta:
        db_table = "project_module"
    
    def __str__(self):
        return self.module_name

priorityChoices = (
    ("High","High"),
    ("Medium","Medium"),
    ("Low","Low"),
)

class Task(models.Model):
    project_module = models.ForeignKey(ProjectModule,on_delete=models.CASCADE)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    task_name = models.CharField(max_length=100)
    
    priority = models.CharField(max_length=100,choices=priorityChoices)
    description = models.TextField()
    status = models.ForeignKey(Status,on_delete=models.CASCADE)
    totalMinutes = models.PositiveIntegerField()
    is_assigned = models.BooleanField(default=False)
    
    
    class Meta:
        db_table="task"
        
    def __str__(self):
        return self.task_name
        

    
class Bug(models.Model):
    project_module = models.ForeignKey(ProjectModule, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    bug_name = models.CharField(max_length=100)
    priority = models.CharField(max_length=100, choices=priorityChoices)
    description = models.TextField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    totalMinutes = models.PositiveIntegerField()
    is_assigned = models.BooleanField(default=False)

    class Meta:
        db_table = "bug"
        
    def __str__(self):
        return self.bug_name
    
class UserTask(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    task = models.ForeignKey(Task,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    updated_at = models.DateTimeField(auto_now=True,null=True,blank=True)
    
    class Meta:
        db_table="user_task"
        
    def __str__(self):
        # return self.user.username
        return self.task.task_name + " -> " + self.user.username

project/forms.py
from django import forms
from .models import Project,ProjectTeam,ProjectModule,Task,UserTask,Status,Bug
from user.models import User

class ProjectCreationForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'startDate': forms.DateInput(attrs={'type': 'date'}),
            'endDate': forms.DateInput(attrs={'type': 'date'})
        }
        
class ProjectTeamCreationForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_manager=True))
    class Meta:
        model = ProjectTeam
        fields = '__all__'
        
class ProjectStatusCreationForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'
        
class ModuleCreationForm(forms.ModelForm):
    class Meta:
        model = ProjectModule
        fields = '__all__'
        widgets = {
            'startDate': forms.DateInput(attrs={'type': 'date'})
        }
        
class TaskCreationForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        
class TaskAssignForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.filter(is_developer=True))
    class Meta:
        model = UserTask
        fields = '__all__'
        
class BugCreationForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = '__all__'

project/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from user.models import User
from .models import Project,ProjectTeam,ProjectModule,Task,UserTask,Status,Bug
from .forms import ProjectCreationForm,ProjectTeamCreationForm,ModuleCreationForm,TaskCreationForm,TaskAssignForm,ProjectStatusCreationForm,BugCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic.edit import UpdateView

# Create your views here.
class ProjectCreationView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = "project/create.html"
    success_url = "/project/list"

class ProjectListView(ListView):
    model = Project
    template_name = "project/list.html"
    context_object_name = "project"
    
class ProjectTeamCreateView(CreateView):
    model = ProjectTeam
    form_class = ProjectTeamCreationForm    
    template_name = 'project/create_team.html'
    success_url = '/project/list/'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        project_id = self.request.GET.get('project_id')
        
        if project_id:
            project = get_object_or_404(Project, id=project_id)
            kwargs['initial']['project'] = project
        return kwargs

def project_team_view(request, id):
    project = ProjectTeam.objects.prefetch_related('user').filter(project_id=id)
    
    team_members = []
    for item in project:
        user = get_object_or_404(User, id=item.user_id)
        team_members.append({
            'username': user.username,
        })
        
    project = get_object_or_404(Project, id=id)
        
    return render(request, 'project/project_team.html', {'team_members': team_members, 'project' : project})

class ProjectUpdateview(UpdateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = "project/update.html"
    success_url = "/project/list"
    
class ProjectDetailView(DetailView):
   model = Project
   context_object_name = "project"
   template_name = "project/detail.html"
        
def delete_project(request,id):
    project = Project.objects.get(id=id)
    
    project.delete()
    
    return HttpResponseRedirect("/project/list")

class ProjectTeamDetailView(DetailView):
   model = Project
   context_object_name = "project"
   template_name = "project/detail.html"
   
   
class ProjectStatusCreateView(CreateView):
    template_name = "project/status.html"
    model = Status
    success_url = "/project/list"
    form_class = ProjectStatusCreationForm
    

def taskStatusUpdateView(request,id):
    task = Task.objects.get(id=id)
    
    if task.status.status_name == "Not-started":
        task.status_id = 2
    elif task.status.status_name == "In-progress":
        task.status_id = 3
    elif task.status.status_name == "Testing":
        task.status_id = 4
        
    task.save()
    
    return redirect(reverse('developer_dashboard'))

class ModuleCreationView(CreateView):
    model = ProjectModule
    form_class = ModuleCreationForm
    template_name = "project/create_module.html"
    success_url = "/project/list_module"
    
class ModuleListView(ListView):
    model = ProjectModule
    template_name = "project/list_module.html"
    context_object_name = "module"
    
class ModuleUpdateview(UpdateView):
    model = ProjectModule
    form_class = ModuleCreationForm
    template_name = "project/update_module.html"
    success_url = "/project/list_module"
    
class ModuleDetailView(DetailView):
   model = ProjectModule
   context_object_name = "module"
   template_name = "project/detail_module.html"
        
def delete_module(request,id):
    module = ProjectModule.objects.get(id=id)
    
    module.delete()
    
    return HttpResponseRedirect("/project/list_module")

class TaskCreationView(CreateView):
    model = Task
    form_class = TaskCreationForm
    template_name = "project/create_task.html"
    success_url = "/project/list_task"

class TaskListView(ListView):
    model = Task
    template_name = "project/list_task.html"
    context_object_name = "task"
    
class TaskUpdateview(UpdateView):
    model = Task
    form_class = TaskCreationForm
    template_name = "project/update_task.html"
    success_url = "/project/list_task"
    
class TaskDetailView(DetailView):
   model = Task
   context_object_name = "task"
   template_name = "project/detail_task.html"
        
def delete_task(request,id):
    task = Task.objects.get(id=id)
    
    task.delete()
    
    return HttpResponseRedirect("/project/list_task")

class TaskAssignView(CreateView):
    model = UserTask
    form_class = TaskAssignForm
    template_name = "project/task_assign.html"
    success_url = "/project/list"
    
class BugListView(ListView):
    model = Bug
    template_name = "project/list_bug.html"
    context_object_name = "bug"
    

class BugCreationView(CreateView):
    model = Bug
    form_class = BugCreationForm
    template_name = "project/add_bug.html"
    success_url = "/project/list_bug"
    
class BugUpdateview(UpdateView):
    model = Bug
    form_class = BugCreationForm
    template_name = "project/update_bug.html"
    success_url = "/project/list_bug"
    
class BugDetailView(DetailView):
   model = Bug
   context_object_name = "bug"
   template_name = "project/detail_bug.html"
   
def delete_bug(request,id):
    bug = Bug.objects.get(id=id)
    
    bug.delete()
    
    return HttpResponseRedirect("/project/list_bug")

# def bugStatusUpdateView(request,id):
#     bug = Bug.objects.get(id=id)
    
#     if bug.status.status_id == 1:
#         bug.status_id = 2
#     elif bug.status.status_id == 2:
#         bug.status_id = 3
#     elif bug.status.status_id == 3:
#         bug.status_id = 4
        
#     bug.save()
    
#     return redirect(reverse('developer_dashboard'))

templates/project/create.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
{% endblock sidebar %}

{% block navbar %}
{% endblock navbar %}

{% block div %}
{% endblock div %}

{% block content %}
<main class="main-content mt-0 ps">
    <div class="pt-5 pb-11">
      <div class="container">
        <div class="row">
          <div class="col-lg-5 text-center mx-auto">
            <h2 class="text-dark">Create Project</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-lg-n10 mt-md-n11 mt-n10 justify-content-center">
        <div class="col-xl-4 col-lg-5 col-md-7 mx-auto">
          <div class="card z-index-0">
            <div class="card-body">
              <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.name|as_crispy_field}}
                    </div>
                  {% comment %} <input type="text" class="form-control" placeholder="Name" aria-label="Name"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.description|as_crispy_field}}
                    </div>
                  {% comment %} <input type="email" class="form-control" placeholder="Email" aria-label="Email"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.technology|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.estimated_hours|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.startDate|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.endDate|as_crispy_field}}
                    </div>
                <div class="text-center">
                    <input type="submit" value="Create" class="btn bg-gradient-dark w-100 my-4 mb-2" />
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></main>
{% endblock content %}

templates/project/create_module.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
{% endblock sidebar %}

{% block navbar %}
{% endblock navbar %}

{% block div %}
{% endblock div %}

{% block content %}
<main class="main-content mt-0 ps">
    <div class="pt-5 pb-11">
      <div class="container">
        <div class="row">
          <div class="col-lg-5 text-center mx-auto">
            <h2 class="text-dark">Create Module</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-lg-n10 mt-md-n11 mt-n10 justify-content-center">
        <div class="col-xl-4 col-lg-5 col-md-7 mx-auto">
          <div class="card z-index-0">
            <div class="card-body">
              <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.project|as_crispy_field}}
                    </div>
                  {% comment %} <input type="text" class="form-control" placeholder="Name" aria-label="Name"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.module_name|as_crispy_field}}
                    </div>
                  {% comment %} <input type="email" class="form-control" placeholder="Email" aria-label="Email"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.description|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.estimated_hours|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.status|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.startDate|as_crispy_field}}
                        {% comment %} {{startDate = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))}} {% endcomment %}
                    </div>
                <div class="text-center">
                    <input type="submit" value="Create" class="btn bg-gradient-dark w-100 my-4 mb-2" />
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></main>
{% endblock content %}

templates/project/create_task.html
{% extends "../base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block sidebar %}
{% endblock sidebar %}

{% block navbar %}
{% endblock navbar %}

{% block div %}
{% endblock div %}

{% block content %}
<main class="main-content mt-0 ps">
    <div class="pt-5 pb-11">
      <div class="container">
        <div class="row">
          <div class="col-lg-5 text-center mx-auto">
            <h2 class="text-dark">Create Task</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mt-lg-n10 mt-md-n11 mt-n10 justify-content-center">
        <div class="col-xl-4 col-lg-5 col-md-7 mx-auto">
          <div class="card z-index-0">
            <div class="card-body">
              <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.project|as_crispy_field}}
                    </div>
                  {% comment %} <input type="text" class="form-control" placeholder="Name" aria-label="Name"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.project_module|as_crispy_field}}
                    </div>
                  {% comment %} <input type="email" class="form-control" placeholder="Email" aria-label="Email"> {% endcomment %}
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.task_name|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.priority|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.description|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.status|as_crispy_field}}
                    </div>
                </div>
                <div class="mb-3">
                    <div class="form-control-sm">
                        {{form.totalMinutes|as_crispy_field}}
                    </div>
                </div>
                <div class="text-center">
                    <input type="submit" value="Create" class="btn bg-gradient-dark w-100 my-4 mb-2" />
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></main>
{% endblock content %}

templates/project/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous"
    />
    <style>
         body {
            background-image: url('https://raw.githubusercontent.com/creativetimofficial/public-assets/master/argon-dashboard-pro/assets/img/signup-cover.jpg'); /* Specify the path to your background image */
            background-size: cover; /* Cover the entire background */
            background-repeat: no-repeat; /* Do not repeat the background image */
        }
        .container {
            padding-left: 20px; /* Adjust this value as needed */
            padding-right: 20px; /* Adjust this value as needed */
            background-color: #ffffff; /* Light background color */
        }
        .module {
            margin-bottom: 20px;
            font-size: 20px;
            font-style: italic;
        }
        .task {
            margin-left: 20px;
            margin-bottom: 10px;
        }
        .bug {
            margin-left: 40px;
            margin-bottom: 5px;
            text-decoration: underline;
        }
        .module-name {
            font-size: larger;
            font-style: italic;
            font-weight: bold; /* Make the module name bold */
        }
        /* Custom colors */
        .description,
        .technology,
        .date,
        .project-name {
            font-weight: bold; /* Make the text bold */
        }
        .description {
            color: #dc3545; /* Red */
        }
        .technology {
            color: #ffc107; /* Yellow */
        }
        .date {
            color: #17a2b8; /* Cyan */
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="mt-5">
          <h3>Project</h3>
          <ul class="list-group">
            <li class="list-group-item module project-name"><strong>{{ project.name }}</strong></li>
            <li class="list-group-item module description">Description: {{ project.description }}</li>
            <li class="list-group-item module technology">Technology: {{ project.technology }}</li>
            <li class="list-group-item module date">Start Date: {{ project.startDate }}</li>
            <li class="list-group-item module date">End Date: {{ project.endDate }}</li>
          </ul>
        </div>
        <div class="mt-5">
            <h3>Modules</h3>
            <ul class="list-group">
                {% for module in project.projectmodule_set.all %}
                <li class="list-group-item module module-name">{{ module.module_name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="mt-5">
            <h3>Tasks</h3>
            {% for module in project.projectmodule_set.all %}
            <h4 class="module-name">{{ module.module_name }}</h4>
            <ul class="list-group">
                {% for task in module.task_set.all %}
                <li class="list-group-item task">
                    <strong>Task Name : {{ task.task_name }}</strong> 
                    <span class="badge badge-info">Status: {{ task.status }}</span> 
                    <span class="badge badge-warning">Priority: {{ task.priority }}</span>
                    <ul class="list-group mt-2">
                        {% for bug in task.bug_set.all %}
                        <li class="list-group-item bug">
                            <span>Bug : {{ bug.bug_name }}</span> 
                            <span class="badge badge-info">Status: {{ bug.status }}</span> 
                            <span class="badge badge-warning">Priority: {{ bug.priority }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/project/detail_bug.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous"
    />
</head>
<body>
    <div class="d-flex justify-content-center" style="margin-top: 5%;">
      <div class="card" style="width: 18rem;" >
        <div class="card-body">
          <h5 class="card-title">{{bug.task}}</h5>
          <h5 class="card-title">{{bug.bug_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{bug.description}}</h6>
          <p class="card-text mt-3">Project: {{bug.project}}</p>

          <p class="card-text">Module: {{bug.project_module}}</p>
          <p class="card-text">Priority: {{bug.priority}}</p>
          <p class="card-text">Status: {{bug.status}}</p>
          <p class="card-text">Total Minutes: {{bug.totalMinutes}}</p>
        </div>
      </div>
    </div>
</body>
</html>

templates/project/detail_module.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous"
    />
</head>
<body>
    <div class="d-flex justify-content-center" style="margin-top: 5%;">
      <div class="card" style="width: 18rem;" >
        <div class="card-body">
          <h5 class="card-title">{{module.module_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{module.description}}</h6>
          <p class="card-text mt-3">Project: {{module.project}}</p>
          <p class="card-text">Estimated Hours: {{module.estimated_hours}}</p>
          <p class="card-text">Status: {{module.status}}</p>
          <p class="card-text">Start Date: {{module.startDate}}</p>
        </div>
      </div>
    </div>
</body>
</html>

templates/project/detail_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link 
    rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous"
    />
</head>
<body>
    <div class="d-flex justify-content-center" style="margin-top: 5%;">
      <div class="card" style="width: 18rem;" >
        <div class="card-body">
          <h5 class="card-title">{{task.task_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{task.description}}</h6>
          <p class="card-text mt-3">Project: {{task.project}}</p>
          <p class="card-text">Module: {{task.project_module}}</p>
          <p class="card-text">Priority: {{task.priority}}</p>
          <p class="card-text">Status: {{task.status}}</p>
          <p class="card-text">Total Minutes: {{task.totalMinutes}}</p>
        </div>
      </div>
    </div>
</body>
</html>

templates/project/status.html
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>